server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:gateway-service}
  cloud:
    gateway:
      routes:
        - id: inventory-route
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/productos/**
        - id: operator-route
          uri: lb://OPERATOR-SERVICE
          predicates:
            - Path=/api/operaciones/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
