server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:gateway-service}
  cloud:
    gateway:
      routes:
        - id: inventory-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/productos/**
        - id: operator-route
          uri: lb://operator-service
          predicates:
            - Path=/api/operaciones/**
    globalcors:
      corsConfigurations:
        "[/**]":
          allowedOrigins:
            - "https://tiendagimnasio.vercel.app"
          allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT
            - DELETE
          allowedHeaders:
            - "*"
          allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
