server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: inventory-route
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/productos/**
        - id: operator-route
          uri: lb://OPERATOR-SERVICE
          predicates:
            - Path=/api/operaciones/**
